---
version: '3.8'
services:
  prd-portainer-app:
    image: docker-registry.theautomation.nl/coen/prd-portainer-app:latest
    container_name: prd-portainer-app
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - prd-portainer-app-data:/data

volumes:
  prd-portainer-app-data:
    name: prd-portainer-app-data

networks:
  reverse-proxy:
    driver: bridge
    name: reverse-proxy
    ipam:
      config:
        - subnet: 172.20.0.0/16
